name: Tanvi CI/CD Pipeline

on:
 push:
  branches: [main]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:

  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Build Website
    run: echo "Building Tanvi Portfolio"

  - name: Test Website
    run: echo "Testing website files"

  - name: Deploy
    run: echo "Deploying website"
